import {Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Provider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Providers>
       {children}
       </Providers>
       <Toaster />
      </body>
    </html>
  );
}
